[package]
authors = ["Brian L. Troutwine <blt@postmates.com>"]
description = "an unbounded mpsc with bounded memory"
keywords = ["channel", "bounded", "mpsc", "asynchronous"]
license = "MIT"
name = "hopper"
readme = "README.md"
repository = "https://github.com/postmates/hopper"
version = "0.3.3"

[dev-dependencies]
quickcheck = "0.4"
tempdir = "0.3"

[dependencies]
zlo = "0.1"
serde = "1.0"
